### ISSUE TITLE
Disordered cutoff for propensity score

### ISSUE THREAD

**Issue by zyh4482** [YihePang/DisoFLAG#1]
Would you mind telling me what the cutoff is for propensity score to determine whether the residue is disordered or not?

**Comment by YihePang** [comment]
The binary result cutoffs for disordered regions are given in the code. Please refer to the source code for details.

**Comment by zyh4482** [comment]
Noted with thanks. 

BTW, your model code has some mistaken idents which caused error message. Additionally, your loading data function does not take the empty line into account, which would have some incompatible issues with other tools. A small modification as follow: 

```
def load_file_2_data(file_path):
    loadfile = open(file_path,"r")
    load_f = []
    for line in loadfile:
        line=line.strip('\n')
        if line:  # Ignore empty lines
            load_f.append(line)
    loadfile.close()
    
    load_data = []
    for i in range(len(load_f)):
        if i % 2 == 0:
            load_data.append(load_f[i:i+2])
    return load_data
```
Hope these info might be helpful.

**Comment by valentynbez** [comment]
In case anyone else would be searching for these, since it is not that obvious: 
https://github.com/YihePang/DisoFLAG/blob/bf629358aacfc8e57d004e32aa49c29a8a9ef953/evaluator.py#L134-L142

**Comment by zyh4482** [comment]
@valentynbez I would not suggest to use this tool for disorder prediction. I found large discrepancies between this and other state-of-art methods. If you combine this result with other tools using similar strategies like CAID, you will get disaster annotations.

**Comment by valentynbez** [comment]
@zyh4482 could you please specify what is considered SOTA in this domain?
